#!/bin/sh
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the GNU General Public License
#    as published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#

# modify the following to suit your environment 
export MP3_PATH="~/mp3"

# title and version
echo ""
echo "Ices Launcher v1.0"
echo "----------------------"


# Update playlist 
echo -n "    Updating playlist..."
if find $MP3_PATH -iname \*.mp3 > /usr/local/icecast/conf/playlist.txt
then
        echo "Done"
else
        echo "There was an ERROR creating the playlist."
fi


# Launch Ices with the correct flags and pointing to the new playlist
echo -n "    Launching ices..."
echo "Done"
echo "----------------------"
echo "Ices Launcher Complete"
echo ""

/usr/local/icecast/bin/ices -S builtin -P playthis -n ' ' -r -s -F /usr/local/icecast/conf/playlist.txt
	
# bitrate control flag  -b 128
exit 0
