<?php
/* This are the vars you may need to modify */
/* Some may be placed in conf files */
/* Some may be generated by your application */
$url = 'http://api.zemanta.com/services/rest/0.0/'; //Should be in a conf file
$format = 'xml'; // May depend of your application context
$text = "barack obama"; // May depend of your application context
$key = "kn43v6s3db9xdndsg9fhb5gb"; //Should be in a conf file
$method = "zemanta.suggest"; // May depend of your application context

/* It is easier to deal with arrays */
$args = array(
'method'=> $method,
'api_key'=> $key,
'text'=> $text,
'format'=> $format
);

/* Here we build the data we want to POST to Zementa */
$data = "";
foreach($args as $key=>$value)
{
$data .= ($data != "")?"&":"";
$data .= urlencode($key)."=".urlencode($value);
}


/* Initialisation of curl */
$ch = curl_init();
/* Setup of the url*/
curl_setopt($ch, CURLOPT_URL, $url);
/* We want a post request */
curl_setopt($ch, CURLOPT_POST, 1);
/* Here we give to curl the data we want to send to Zementa*/
curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
/* We setup the response method of curl */
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
/* Execute curl and fetch the result */
$response = curl_exec ($ch);
/* Close curl connection */
curl_close ($ch);
?>
