<?php
/* This are the vars you may need to modify */
/* Some may be placed in conf files */
/* Some may be generated by your application */
$url = 'http://api.zemanta.com/services/rest/0.0/'; //Should be in a conf file
$format = 'xml'; // May depend of your application context
$text = "barack obama"; // May depend of your application context
$key = "kn43v6s3db9xdndsg9fhb5gb"; //Should be in a conf file
$method = "zemanta.suggest"; // May depend of your application context

/* It is esayer to deal with arrays */
$args = array(
'method'=> $method,
'api_key'=> $key,
'text'=> $text,
'format'=> $format
);

/* Here we build the data we want to POST to Zementa */
$data = "";
foreach($args as $key=>$value)
{
$data .= ($data != "")?"&":"";
$data .= urlencode($key)."=".urlencode($value);
}

/* Here we build the POST request */
$params = array('http' => array(
'method' => 'POST',
'Content-type'=> 'application/x-www-form-urlencoded',
'Content-length' =>strlen( $data ),
'content' => $data
));

/* Here we send the post request */
$ctx = stream_context_create($params); // We build the POST context of the request
$fp = @fopen($url, 'rb', false, $ctx); // We open a stream and send the request
if ($fp)
{
/* Finaly, herewe get the response of Zementa */
$response = @stream_get_contents($fp);
if ($response === false)
{
$response = "Problem reading data from ".$url.", ".$php_errormsg;
}
fclose($fp); // We close the stream
}
else
{
$response = "Problem reading data from ".$url.", ".$php_errormsg;
}
?>
